parameters:
    dedipanel.key_store.file.class: Dedipanel\PHPSeclibWrapperBundle\KeyStore\FileKeyStore
    dedipanel.key_store.file.path: '%kernel.root_dir%/keys/'
    dedipanel.key_helper.class: Dedipanel\PHPSeclibWrapperBundle\KeyHelper
    dedipanel.connection_manager.class: Dedipanel\PHPSeclibWrapperBundle\Connection\ConnectionManager
    dedipanel.connection_manager.debug: false

services:
    dedipanel.key_store.file:
        class: %dedipanel.key_store.file.class%
        arguments: [ %dedipanel.key_store.file.path ]

    dedipanel.key_helper:
        class: %dedipanel.key_helper.class%
        arguments: [ @dedipanel.key_store.file ]

    dedipanel.connection_manager:
        class: %dedipanel.connection_manager.class%
        arguments: [ @logger, %dedipanel.connection_manager.debug% ]
