parameters:
    dedipanel.key_store.file.class: Dedipanel\PHPSeclibWrapperBundle\KeyStore\FileKeyStore
    dedipanel.key_store.file.path: '%kernel.root_dir%/keys/'
    dedipanel.key_helper.class: Dedipanel\PHPSeclibWrapperBundle\Helper\KeyHelper
    dedipanel.connection_manager.class: Dedipanel\PHPSeclibWrapperBundle\Connection\ConnectionManager
    dedipanel.connection_manager.debug: false

services:
    dedipanel.key_store.file:
        class: %dedipanel.key_store.file.class%
        arguments: [ %dedipanel.key_store.file.path% ]

    dedipanel.key_helper:
        class: %dedipanel.key_helper.class%
        arguments: [ @dedipanel.connection_manager, @dedipanel.key_store.file ]

    dedipanel.connection_manager:
        class: %dedipanel.connection_manager.class%
        arguments: [ @logger, %dedipanel.connection_manager.debug% ]
        tags:
            - { name: monolog.logger, channel: phpseclib }

    dedipanel.listener.auto_load_key:
        class: Dedipanel\PHPSeclibWrapperBundle\EventListener\AutoKeyLoaderListener
        arguments: [ @dedipanel.key_store.file ]
        tags:
          - { name: doctrine.event_listener, event: postLoad, method: postLoad }

    dedipanel.extension.sftp:
        class: Dedipanel\PHPSeclibWrapperBundle\Extension\SFTPExtension
        tags:
            - { name: twig.extension }

    dedipanel.sftp_factory:
        class: Dedipanel\PHPSeclibWrapperBundle\SFTP\SFTPItemFactory

