filter:
    excluded_paths:
        - 'vendor/*'
        - 'app/*'
        - 'web/*'
tools:
    php_cpd: true
    php_pdepend: true
    php_cs_fixer:
        config:
            level: all
    sensiolabs_security_checker: true
    php_loc: true
    php_hhvm: true
