language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - composer install --prefer-dist
  - chmod +x Tests/bootstrap.sh
  - Tests/bootstrap.sh configure
  - Tests/bootstrap.sh test

script: phpunit

after_script:
  - Tests/bootstrap.sh clean
