language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

env:
  - SYMFONY_VERSION=^2.8
  - SYMFONY_VERSION=^3.4
  - SYMFONY_VERSION=^4.1

matrix:
  exclude:
    - php: 5.6
      env: SYMFONY_VERSION=^4.1

before_install:
  - composer self-update
  - phpenv config-rm xdebug.ini || true
  - composer require --no-update symfony/framework-bundle:${SYMFONY_VERSION}

before_script:
  - chmod +x Tests/bootstrap.sh
  - Tests/bootstrap.sh configure
  - Tests/bootstrap.sh test

install: COMPOSER_MEMORY_LIMIT=-1 composer install --prefer-dist

script: vendor/bin/phpunit

after_script:
  - Tests/bootstrap.sh clean
