language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - chmod +x Tests/bootstrap.sh
  - Tests/bootstrap.sh configure
  - Tests/bootstrap.sh test

script: phpunit

after_script:
  - Tests/bootstrap.sh clean
